// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://heizvkxctobyhvkqxlhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlaXp2a3hjdG9ieWh2a3F4bGh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MzQ1NDksImV4cCI6MjA1NTIxMDU0OX0.g7Ssw3qAfNRlx1l7MGHzWJ7EvXydfNV0K8NqUb5sAd4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);